apiVersion: v1
kind: Service
metadata:
  name: hello-ibm
  namespace: system
  labels:
    service: hello-ibm
spec:
  selector:
    app: hello-ibm
  type: NodePort
  ports:
   - port: 3000
     targetPort: 3000
     nodePort: 32660